export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
export const SET_CURRENT_QUIZ_MEMO = 'SET_CURRENT_QUIZ_MEMO';
export const FINISH_CURRENT_QUIZ = 'FINISH_CURRENT_QUIZ';
